### PR TITLE
Live dev merge into dev

### PR DESCRIPTION
**Pull request by ergomez0201**
Added boilerplate in live-dev
-Server listening on port 3000
-Webpack configured
-Entry into index.js and App.jsx

### CODE REVIEW

**Review by astholden — APPROVED** [review]

**Review by jessllee — APPROVED** [review]
We finally got our base files and boilerplate ready, and the server runs.

**Review by JuiceBawks — APPROVED** [review]

**Review by JuiceBawks — APPROVED** [review]

**Review by jessllee — APPROVED** [review]
We finally got the boilerplate and server running.

**Review by JuiceBawks — APPROVED** [review]

**Review by astholden — APPROVED** [review]
This is timeconsuming

**Review by JuiceBawks — APPROVED** [review]

**Review by astholden — APPROVED** [review]

**Review by astholden — APPROVED** [review]

**Review by astholden — APPROVED** [review]

**Review by ergomez0201 — COMMENTED** [review]
All changes approved for boilerplate

**Pull request merged**
